In [5]:
from pynwb import NWBHDF5IO
import numpy as np
import os

# Get the absolute path of the current file
current_file_path = os.path.dirname(os.getcwd())

# Path to your NWB file
file_path = os.path.join(current_file_path, 'test/Screening/572_Screening/Experiment-2/nwb/ecephys.nwb')

raw_io = NWBHDF5IO(file_path, "r")
nwb_in = raw_io.read()


In [6]:
nwb_in

root pynwb.file.NWBFile at 0x4809783472
Fields:
  devices: {
    array <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    GA1 <class 'pynwb.ecephys.ElectrodeGroup'>,
    GA2 <class 'pynwb.ecephys.ElectrodeGroup'>,
    GA3 <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experimenter: ['My Name']
  file_create_date: [datetime.datetime(2024, 7, 25, 12, 10, 8, 945062, tzinfo=tzoffset(None, -25200))]
  identifier: sub-572_exp-2_Screening
  institution: UCLA
  processing: {
    ecephys <class 'pynwb.base.ProcessingModule'>
  }
  session_description: sub-572_exp-2_Screening
  session_start_time: 1900-01-01 00:00:00-08:00
  subject: subject pynwb.file.Subject at 0x4809749744
Fields:
  age__reference: birth
  sex: M
  species: human
  subject_id: 572

  timestamps_reference_time: 1900-01-01 00:00:00-08:00
  units: units <class 'pynwb.misc.Units'>

In [7]:
nwb_in.electrodes

electrodes hdmf.common.table.DynamicTable at 0x4810940912
Fields:
  colnames: ['x' 'y' 'z' 'location' 'group' 'group_name' 'label']
  columns: (
    x <class 'hdmf.common.table.VectorData'>,
    y <class 'hdmf.common.table.VectorData'>,
    z <class 'hdmf.common.table.VectorData'>,
    location <class 'hdmf.common.table.VectorData'>,
    group <class 'hdmf.common.table.VectorData'>,
    group_name <class 'hdmf.common.table.VectorData'>,
    label <class 'hdmf.common.table.VectorData'>
  )
  description: all electrodes
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

In [45]:
# create a list of electrodes:
list(nwb_in.electrodes.label) 

['RA1', 'REC1', 'RAH1']

In [14]:
# load LFP:
import numpy as np

microLFP = np.array(nwb_in.processing['ecephys']['microLFP']['ElectricalSeries'].data)
display(microLFP)
display(microLFP.shape)

array([[-19.409262 , -64.36195  , -92.010994 ],
       [-21.415161 , -57.38958  , -91.39748  ],
       [-25.6193   , -56.376083 , -92.755264 ],
       ...,
       [  7.4415317,  10.44263  ,  -2.3405159],
       [  7.017481 ,   9.555097 ,  -5.576465 ],
       [ 13.60018  ,  13.978219 ,  -0.9910072]], dtype=float32)

(317885, 3)

In [15]:
macroLFP = np.array(nwb_in.processing['ecephys']['macroLFP']['ElectricalSeries'].data)
display(macroLFP)
display(macroLFP.shape)

array([[ -9.42994 , -30.85329 , -83.49613 ],
       [-10.437127, -32.134872, -85.510445],
       [-11.993601, -32.501537, -87.89078 ],
       ...,
       [ 18.402233,  10.425636,  37.239197],
       [ 20.42166 ,  12.656429,  39.44528 ],
       [ 20.832436,  14.931439,  42.075493]], dtype=float32)

(317883, 3)

In [62]:
# load spikes:
from collections import defaultdict
spikes = defaultdict(list)

for spike_times, electrodes in zip(nwb_in.units['spike_times'], nwb_in.units['electrodes']):
    spikes[list(electrodes.label)[0]].append(spike_times)

display(spikes.keys())
display(spikes['RA1'][1])

dict_keys(['RA1', 'REC1', 'RAH1'])

array([  3.68271661,   4.3180604 ,   4.32440424,   5.50477934,
         5.51459169,   7.75537205,   7.8764658 ,   7.89396572,
         8.53808975,   9.01002693,  11.57030678,  11.60655785,
        11.62974548,  11.85099506,  12.28536987,  12.70605755,
        12.97937012,  13.01249504,  13.12462044,  13.75261879,
        14.35518169,  14.42455673,  14.57824421,  14.59021282,
        15.58255672,  15.71489906,  15.95980549,  16.46849251,
        17.13802338,  18.02318001,  18.7334919 ,  19.61699104,
        19.63855362,  19.73396111,  19.74064827,  19.81021118,
        20.06461716,  20.58267975,  20.75921059,  21.21620941,
        21.25764656,  21.56889725,  22.29267883,  22.86805344,
        23.5795517 ,  23.6003952 ,  23.81627083,  24.11623955,
        24.13864708,  24.36092758,  24.36380196,  24.71692657,
        25.16483307,  25.75623894,  25.77830124,  25.88370705,
        25.98042679,  26.16261292,  26.18008232,  26.86045837,
        27.02827072,  27.12692642,  27.23233223,  27.52

In [63]:
# load average waveforms:
from collections import defaultdict
waveform_mean = defaultdict(list)

for waveform, electrodes in zip(nwb_in.units['waveform_mean'], nwb_in.units['electrodes']):
    waveform_mean[list(electrodes.label)[0]].append(waveform)

display(waveform_mean.keys())
display(waveform_mean['RA1'][1])

dict_keys(['RA1', 'REC1', 'RAH1'])

array([  4.1024513 ,   4.263457  ,   4.7624555 ,   5.4079843 ,
         5.9183803 ,   6.0406766 ,   5.680064  ,   4.9812202 ,
         4.3131905 ,   4.141784  ,   4.819681  ,   6.366548  ,
         8.330776  ,   9.808917  ,   9.648799  ,   6.7937374 ,
         0.66389877,  -8.557275  , -19.843876  , -31.503942  ,
       -41.573265  , -48.31081   , -50.64163   , -48.409157  ,
       -42.36385   , -33.90427   , -24.666027  , -16.095995  ,
        -9.140905  ,  -4.1284943 ,  -0.8470777 ,   1.2358843 ,
         2.7119968 ,   4.020488  ,   5.346563  ,   6.6399574 ,
         7.719865  ,   8.40808   ,   8.633002  ,   8.468778  ,
         8.105083  ,   7.7703853 ,   7.645949  ,   7.8056974 ,
         8.202144  ,   8.698234  ,   9.12756   ,   9.357293  ,
         9.330442  ,   9.075078  ,   8.681676  ,   8.26125   ,
         7.902042  ,   7.6406264 ,   7.4560266 ,   7.286065  ,
         7.057394  ,   6.7168183 ,   6.252585  ,   5.699006  ,
         5.124253  ,   4.6068583 ,   4.2097654 ,   3.96