In [68]:
from pynwb import NWBHDF5IO
import numpy as np
import os

# Get the absolute path of the current file
current_file_path = os.path.dirname(os.getcwd())

# Path to your NWB file
file_path = os.path.join(current_file_path, 'test/Screening/572_Screening/Experiment-2/nwb/ecephys.nwb')

raw_io = NWBHDF5IO(file_path, "r")
nwb_in = raw_io.read()


/opt/miniconda3/envs/nwbPipeline/lib/python3.8/site-packages/hdmf/utils.py:668: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.5.0 because version 1.8.0 is already loaded.
  return func(args[0], **pargs)
/opt/miniconda3/envs/nwbPipeline/lib/python3.8/site-packages/hdmf/utils.py:668: UserWarning: Ignoring cached namespace 'core' version 2.6.0-alpha because version 2.7.0 is already loaded.
  return func(args[0], **pargs)
/opt/miniconda3/envs/nwbPipeline/lib/python3.8/site-packages/hdmf/utils.py:668: UserWarning: Ignoring cached namespace 'hdmf-experimental' version 0.1.0 because version 0.5.0 is already loaded.
  return func(args[0], **pargs)


In [69]:
nwb_in

root pynwb.file.NWBFile at 0x5293362096
Fields:
  devices: {
    array <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    GA1 <class 'pynwb.ecephys.ElectrodeGroup'>,
    GA2 <class 'pynwb.ecephys.ElectrodeGroup'>,
    GA3 <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experimenter: ['My Name']
  file_create_date: [datetime.datetime(2024, 7, 24, 18, 56, 14, 520909, tzinfo=tzoffset(None, -25200))]
  identifier: sub-572_exp-2_Screening
  institution: UCLA
  processing: {
    ecephys <class 'pynwb.base.ProcessingModule'>
  }
  session_description: sub-572_exp-2_Screening
  session_start_time: 1900-01-01 00:00:00-08:00
  subject: subject pynwb.file.Subject at 0x5293605744
Fields:
  age__reference: birth
  sex: M
  species: human
  subject_id: 572

  timestamps_reference_time: 1900-01-01 00:00:00-08:00
  units: units <class 'pynwb.misc.Units'>

In [70]:
nwb_in.electrodes

electrodes hdmf.common.table.DynamicTable at 0x5293361088
Fields:
  colnames: ['x' 'y' 'z' 'location' 'group' 'group_name' 'label']
  columns: (
    x <class 'hdmf.common.table.VectorData'>,
    y <class 'hdmf.common.table.VectorData'>,
    z <class 'hdmf.common.table.VectorData'>,
    location <class 'hdmf.common.table.VectorData'>,
    group <class 'hdmf.common.table.VectorData'>,
    group_name <class 'hdmf.common.table.VectorData'>,
    label <class 'hdmf.common.table.VectorData'>
  )
  description: all electrodes
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

In [71]:
# load LFP:
import numpy as np

np.array(nwb_in.processing['ecephys']['microLFP']['ElectricalSeries'].data)

array([[-19.409262 , -64.36195  , -92.010994 ],
       [-21.415161 , -57.38958  , -91.39748  ],
       [-25.6193   , -56.376083 , -92.755264 ],
       ...,
       [  7.4415317,  10.44263  ,  -2.3405159],
       [  7.017481 ,   9.555097 ,  -5.576465 ],
       [ 13.60018  ,  13.978219 ,  -0.9910072]], dtype=float32)

In [72]:
np.array(nwb_in.processing['ecephys']['macroLFP']['ElectricalSeries'].data)

array([[ -9.42994 , -30.85329 , -83.49613 ],
       [-10.437127, -32.134872, -85.510445],
       [-11.993601, -32.501537, -87.89078 ],
       ...,
       [ 18.402233,  10.425636,  37.239197],
       [ 20.42166 ,  12.656429,  39.44528 ],
       [ 20.832436,  14.931439,  42.075493]], dtype=float32)

In [73]:
# load spikes:
display(nwb_in.units['spike_times'][4])
display(nwb_in.units['electrodes'][4])

array([  3.44606042,   3.55140424,   3.60077929,   3.98734164,
         4.03868532,   4.07212305,   4.73521662,   5.38187313,
         5.38609171,   5.50862312,   5.51696682,   5.55168533,
         5.58952904,   5.70140362,   6.02196598,   6.10415316,
         6.33371544,   6.38193417,   6.41555977,   6.56530952,
         6.61352825,   6.83752823,   6.84509087,   6.92968464,
         6.97190332,   7.26305962,   7.26943445,   7.48987198,
         7.5405283 ,   7.88768435,   8.58402729,   8.70705795,
         9.20140266,   9.23471451,   9.44624615,   9.6979332 ,
        10.45265198,  10.60830879,  10.81524467,  11.14152622,
        11.87943268,  12.02065086,  12.2320261 ,  12.24015141,
        12.25480747,  12.87530708,  12.95730782,  13.12674522,
        13.18058777,  14.031744  ,  14.04293156,  14.547369  ,
        14.76293182,  15.64790058,  15.76639938,  15.9127121 ,
        15.93727398,  16.36218071,  16.39299393,  16.59505463,
        17.03017998,  17.09277344,  17.27399254,  18.18

x      y      z location  \
id                                 
0   111.0  111.0  111.0       RA   

                                                group group_name label  
id                                                                      
0   GA1 pynwb.ecephys.ElectrodeGroup at 0x52933629...        GA1   RA1

In [74]:
# load average waveforms:
nwb_in.units['waveform_mean'][4]

array([  9.62896  ,   9.9976015,  10.456426 ,  10.863098 ,  11.059652 ,
        10.946494 ,  10.547112 ,  10.02804  ,   9.651017 ,   9.6589775,
        10.127626 ,  10.837692 ,  11.228202 ,  10.472464 ,   7.6788626,
         2.1704822,  -6.2407517, -17.081472 , -29.218813 , -41.057613 ,
       -50.88904  , -57.29325  , -59.475876 , -57.437016 , -51.925167 ,
       -44.198544 , -35.67609  , -27.589788 , -20.739372 , -15.407544 ,
       -11.435355 ,  -8.406474 ,  -5.86155  ,  -3.4680154,  -1.0993277,
         1.1824551,   3.2121181,   4.8280663,   5.9557695,   6.6409125,
         7.029212 ,   7.3101835,   7.652107 ,   8.153583 ,   8.82623  ,
         9.609009 ,  10.403297 ,  11.112626 ,  11.672705 ,  12.063629 ,
        12.304119 ,  12.433939 ,  12.493416 ,  12.508136 ,  12.483094 ,
        12.406438 ,  12.259322 ,  12.02712  ,  11.707489 ,  11.312751 ,
        10.866467 ,  10.396125 ,   9.924876 ,   9.465118 ,   9.015809 ,
         8.564062 ,   8.09036  ,   7.575663 ,   7.008342 ,   6.3